/// Define a master featurizer and associated compiler from its subfeaturizers
/// (which implement [`FeaturizableSeqFeats`] and [`CompilableSeqFeats`]).
/// 
/// Featurizer
/// ----------
/// At a high level, the featurizer generated by this macro has the
/// following life cycle:
/// 
/// *Compilation*
/// - Compile each of the subfeaturizers from a master configuration type
///   that can be interpreted as a discriminated union of each of
///   the subfeaturizers' user-facing configuration types.
/// - Compile a "context-provider", a struct that helps make some
///   sequence features more efficient. EX: the context-provider can
///   hold a buffer for residue counts (e.g. if residue counts
///   are useful for the sequence features being computed). Those
///   residue counts would be considered a "context" for computing
///   some of those sequence features.
/// 
/// *Featurization*
/// - Given a sequence, first mutably modify the context-provider
///   to represent the "context" of the current sequence.
///   As in the example above, this stage could represent
///   computing the residue counts, which is expected to be used
///   by other features later down the road.
/// - For each subfeaturizer class included in this master featurizer,
///   use the appropriate context (obtained from the context provider)
///   to compute that sequence feature. Map the error type returned
///   by the subfeaturizer to a union "bubble-up" error type.
/// 
/// Using the macro
/// ---------------
/// This macro requires the following template to be filled out:
/// ```
/// /// A featurizer containing two subfeaturizers.
/// /// Isoelectric point + percent residue.
/// // Section 1) Featurizer struct and featurize method
/// pub struct Featurizer {
///     // a. Abbreviated function signature for `featurize`
///     fn featurize(
///         // a.i. variable name for sequence
///         sequence: &aa_canonical_str
///     ) -> Iterator<
///         ..,
///         // a.ii. common or "bubble-up" error type
///         String
///     > {
///         // b. Setup section
///         // b.i. context provider type and name
///         let mut res_counts: ResidueCounts;
///         // b.ii. expensive context computation
///         //       in this case, the `ResidueCounts` are computed once
///         //       and then re-used in the featurization stage
///         res_counts.compute(sequence);
///         // c. Featurization section
///         // c.ii. context adapter
///         #[ftz(context = &res_counts)]
///         // c.iii. error adapter
///         #[ftz(map_err = |err| err.to_string())]
///         // c.i. subfeaturizer type and name
///         let isoelectric_point: IsoelectricPoint;
///         // c.ii. context adapter
///         #[ftz(context = &res_counts)]
///         // c.iii. error adapter
///         #[ftz(map_err = |infallible| unreachable!())]
///         // c.i. subfeaturizer type and name
///         let percent_residue: PercentResidue;
///     }
/// }
/// /// Compiler for the [`Featurizer`] type above.
/// // Section 2) `Compiler`, `compile`, and `context_provider`.
/// pub struct Compiler {
///     // a. Abbreviated function signature for `compile`
///     fn compile(
///         // a.i user-facing compilable type
///         data: &serde_json::Value,
///         feature_id: &str
///     ) -> Result<
///         (),
///         // a.ii common or "bubble-up" error type
///         String
///     >
///     // b. compile impl, which has access to subcompilers
///     //    `isoelectric_point` and `percent_residue`
///     //    because they were used as variable names
///     //    in `featurize` above
///     {
///        if let Ok(data) = serde_json::from_value::<()>(data) {
///            return isoelectric_point.compile(data).map_err(|err| err.to_string())
///        }
///        if let Ok(data) = serde_json::from_value::<PercentResidueUserFacing>(data) {
///            return percent_residue.compile(data).map_err(|err| err.to_string())
///        }
///        Err("unrecognized value".to_string())
///     }
///     // c. context provider intialization, which also has read access to
///     //    fields `isoelectric_point` and `percent_residue`
///     fn context_provider() -> ResidueCounts { ResidueCounts::default() }
/// }
/// ```
/// 
/// The specific information required is described below:
/// 1.  A `Featurizer` struct and `featurize` function template.
///     To fill out the function, one implements:
///     a. An abbreviated `featurize` function signature, consisting of:
///         i.   A sequence variable name.
///         ii.  An error type, viewed as the "union" of all error types
///              returned by subfeaturizers.
///     b. A setup section, consisting of:
///         i.   A context provider type and field name.
///         ii.  An expensive operation done on the sequence that the
///              subfeaturizers may make use of in their `Ctx` associated
///              types. 
///     c. A repetitive featurization section, consisting of repeated:
///         i.   A subfeaturizer type and field name.
///         ii.  An adapter from the context provider type to the required
///              context in a `#[ftz(context = ...)]` expression.
///         iii. An adapter from the subfeaturizer's error type to the
///              common error type in a `#[ftz(map_err = ...)]` expression.
/// 2.  A `Compiler` struct, a `compile` function, and a `context_provider`
///     function. To fill out the `compile` function, one implements:
///     a. A function signature for the `compile` function, consisting of:
///         i.   A data and feature_id argument name.
///         ii.  A user-facing data type.
///         iii. The error type returned on failed compilation, which should
///              been seen as a union of all possible errors returned from
///              a subcompiler.
///     b. The body of the compile function which has access to subcompilers.
///        There is one subcompiler for each field in the featurization section
///        (1.c.i), which corresponds to a compiler type (see [`CompilableSeqFeats`])
///        for the given struct associated with that field name.
///     c. Initialization for the context provider (see 1.b.i).
///        This initialization impl has access to all subfeaturizers, not subcompilers.
/// 
/// [`FeaturizableSeqFeats`]: crate::seq_features::functionality::featurize::FeaturizableSeqFeats
/// [`CompilableSeqFeats`]: crate::seq_features::functionality::compile::CompilableSeqFeats
macro_rules! define_compiler_and_featurizer {
    ($(#[$($docs1:tt)*])* pub struct $featurizer_struct:ident {
        $(#[$($docs2:tt)*])*
        fn featurize($sequence:ident: &aa_canonical_str) -> Iterator<.., $t1:ty> {
            let mut $ctx_field:ident: $ctx_ty:ty;
            $setup_ctx:expr;
            $(#[ftz(context = $use_ctx:expr)] #[ftz(map_err = $map_err:expr)] let $field:ident: $subfeaturizer:ty;)+
        }
    }
    $(#[$($docs3:tt)*])*
    pub struct $compiler_struct:ident {
        $(#[$($docs4:tt)*])*
        fn compile($data:ident: &$t2:ty, $feature_id:ident: &str) -> Result<(), $t3:ty> $compile_impl:block
        fn context_provider() $finish_ctx:block
    }
    ) => {
        $(#[$($docs1)*])*
        pub struct $featurizer_struct {
            $($field: $subfeaturizer,)+
            $ctx_field: $ctx_ty
        }
        impl crate::seq_features::functionality::featdim::FeatDim for $featurizer_struct {
            fn featdim(&self) -> usize {
                0 $(+crate::seq_features::functionality::featdim::FeatDim::featdim(&self.$field))+
            }
        }
        impl $featurizer_struct {
            $(#[$($docs2)*])*
            pub fn featurize(&mut self, $sequence: &aa_canonical_str) -> impl Iterator<Item = Result<f32, $t1>> {
                use crate::seq_features::functionality::{
                    featdim::FeatDim as _,
                    featurize::FeaturizableSeqFeats as _
                };
                let mut result = Vec::with_capacity(self.featdim());
                let $featurizer_struct {
                    $ctx_field,
                    ..
                } = self;
                $setup_ctx;
                $(if self.$field.has_features() {
                    result.extend(
                        self.$field.featurize($sequence, $use_ctx)
                            .map(|r| r.map_err($map_err))
                    )
                };)+
                result.into_iter()
            }
        }
        $(#[$($docs3)*])*
        pub struct $compiler_struct<'a> {
            $($field: <$subfeaturizer as crate::seq_features::functionality::compile::CompilableSeqFeats>::Compiler<'a>),+
        }
        impl<'a> crate::seq_features::functionality::compile::CompilerImplementor<'a> for $compiler_struct<'a> {
            type UserFacing = $t2;
            type Err = $t3;
            type Container = $featurizer_struct;
            $(#[$($docs4)*])*
            fn compile(&mut self, $data: &Self::UserFacing, $feature_id: &'a str) -> Result<(), Self::Err> {
                let $compiler_struct {
                    $($field),+
                } = self;
                $compile_impl
            }
            fn finish(self, feature_ids: &mut Vec<&'a str>) -> Self::Container {
                $(let $field = crate::seq_features::functionality::compile::CompilerImplementor::finish(self.$field, feature_ids);)+
                let $ctx_field = $finish_ctx;
                $featurizer_struct {
                    $($field,)+
                    $ctx_field
                }
            }
        }
        impl crate::seq_features::functionality::compile::CompilableSeqFeats for $featurizer_struct {
            type Compiler<'a> = $compiler_struct<'a>;
        }
    };
}
pub(super) use define_compiler_and_featurizer;