use crate::{
    adapters::SenderHandle,
    datatypes::{
        aa_canonical_str,
        webworker_messages::{
            blocking::webworker_featurize::{RequestPayload, YieldPayload},
            common::featurize::Featurized,
        },
    },
    seq_features::featurize::{Featurizer, FeaturizerCompilation, compile_features},
};
use wasm_bindgen::JsValue;

/// Worker for public endpoint `featurize`.
///
/// Computes sequence features in batches and sends results to the caller
/// in unlabelled (but organized in the order in which sequences were passed in)
/// matrices of data.
///
/// Dev note
/// --------
/// This function is meant to handle requests deserialized from a `JsValue`
/// [`RequestPayload`]. That is guaranteed to deserialize into the
/// [`RequestPayload::Deserialize`] variant. If you pass in the serializable
/// variant, this function will crash the server.
pub async fn webworker_featurize(
    request: RequestPayload,
    mut sender: SenderHandle,
) -> Result<(), JsValue> {
    let RequestPayload::Deserialize {
        batch_size,
        sequences,
        feature_configuration,
    } = request
    else {
        panic!("[webworker_featurize] was given `RequestPayload::Serialize`")
    };
    let FeaturizerCompilation {
        mut featurizer,
        feat_order,
        ..
    } = compile_features::<Featurizer>(&feature_configuration);
    let featdim = feat_order.len();
    let batch_size = (batch_size as usize).min(sequences.len());
    let mut progress = ProgressManager::new(featdim, batch_size);
    for batch_sequences in sequences.chunks(batch_size) {
        for sequence in batch_sequences {
            progress.run_featurizer(&mut featurizer, &sequence);
        }
        sender = progress.flush_progress(sender).await?;
    }
    sender.send_close(&()).await
}
/// A struct for accumulating and sending the current batch results.
struct ProgressManager {
    data: YieldPayload,
}
impl ProgressManager {
    /// Construct a new progress manager struct.
    pub fn new(featdim: usize, batch_size: usize) -> Self {
        Self {
            data: YieldPayload {
                sequence_by_feature_matrix: Vec::with_capacity(batch_size * featdim),
            },
        }
    }
    /// Compute and accumulate a single sequence's features.
    pub fn run_featurizer(&mut self, featurizer: &mut Featurizer, sequence: &aa_canonical_str) {
        let YieldPayload {
            sequence_by_feature_matrix,
            ..
        } = &mut self.data;
        sequence_by_feature_matrix.extend(featurizer.featurize(&sequence).map(Featurized::from));
    }
    /// Serialize and send the current batch of featurization results out to the caller.
    pub async fn flush_progress(&mut self, sender: SenderHandle) -> Result<SenderHandle, JsValue> {
        let sender = sender.send_data(&self.data).await?;
        self.clear();
        Ok(sender)
    }
    /// Clear the data generated by the previous batch of featurization results.
    fn clear(&mut self) {
        let YieldPayload {
            sequence_by_feature_matrix,
        } = &mut self.data;
        sequence_by_feature_matrix.clear();
    }
}
